#!/bin/sh -e

echo "RSync'ing bib and xml files ..."
rsync -4av --delete \
   bibxml bibtex graphics \
   NorNet-Publications.odt NorNet-Publications.docx \
   nornetpp@voksenkollen.proxmox.crnalab.net:/usr/share/wordpress/pub/nornet-publications/

echo ""
echo "Note: the publications page needs to be updated manually with HTML code from NorNet-Publications.html.block!"
