#!/bin/sh -e

echo "RSync'ing bib and xml files ..."
rsync -4av --delete bibxml bibtex graphics nornetpp@voksenkollen.proxmox.crnalab.net:/usr/share/wordpress/pub/nornet-publications/
echo "Note: the publications page needs to be updated manually with HTML code from NorNet-Publications.html!"
